---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      D6E328D82432FB01BE3DFFA7991B5EBFE76CE170,
      8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
