---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-10-13T00-23-17Z
    nameOverride: minio
    env:
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"
      TZ: "America/New_York"
      MINIO_DOMAIN: s3.${SECRET_DOMAIN}
    envFrom:
      - secretRef:
          name: minio
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 9001
          api:
            enabled: true
            port: 9000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "console.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - "console.${SECRET_DOMAIN}"
              - "s3.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /mnt/user/blackelement/minio
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: "minio"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
