kubernetes:
  children:
    master:
      hosts:
        bes-0:
          ansible_host: 10.10.10.50
        bes-1:
          ansible_host: 10.10.10.51
        bes-2:
          ansible_host: 10.10.10.52
    worker:
      hosts:
        bes-3:
          ansible_host: 10.10.10.53
          rook_devices:
            - /dev/sdb
        bes-4:
          ansible_host: 10.10.10.54
          rook_devices:
            - /dev/sdb
        bes-5:
          ansible_host: 10.10.10.55
          rook_devices:
            - /dev/sdb
