# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:UnWfxojXt7l9sQfMkuG1XbtvgOtn,iv:sQXJVYb0+bf9tN39g93qFILb66rLgIYFCgtkto6QA3M=,tag:spACZJHhCrOfqKNe+pRvtw==,type:str]
    api-key: ENC[AES256_GCM,data:aqm510smxydr6dkC4uzkuRckOpvlHwIaurqHvBal4Mdh1zY9Fw+nyw==,iv:d70H1MpdG/kYH9VUCQBD66y4J1CeiOri+YI3+iYlDPc=,tag:kHOMYaRzC/3CAp2Udm4RYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T17:49:20Z"
    mac: ENC[AES256_GCM,data:XdMBhANgEeyADYUSfc3p64xPBVV9ReRWGFzX8MBWcz8fSK1XsMb7BTOjX8UEzohhDqcziEecfrivEV02LSUqGQgQYuorV7KY2F3iwoAkXsz17Z7zBcgUuBUBhvLBuNa0GvHx9HC2Oiv9zT1gnLhQtymR4RSuiLFJVpDplxeD9Ew=,iv:fSeUx6w1V6Jum/Qm8GWaGOEczkzOkiqNe/yuYh6cAWI=,tag:kd9yyrtX1BYSMDmkGjicxQ==,type:str]
    pgp:
        - created_at: "2021-09-27T17:49:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3/0YQQPIqO9AQ//ZdVWqhwYfLdK1HEZBPha19CLRYAaE6WBmUVkSKZq42GR
            Zq1qRYz1kd8ysP1wRRQ/beBNPPiltB0mPcgu7bGfmV5HoAWFkGAPL0ZW+zKTe2aS
            ynO6d+9gy0t7QgiIKN7/o4dmZrR083/SbYTuLmGnbmcsNkHmrQWfVtMTVSub5AEV
            ROHsPKMLDaWYykP27gdIV/iLu0l/9zoRyKlEwldn5axT/royvivl5fpofHRjclE/
            U2aTRbudmAHZWMrrZecV6PhDlY2/L7U1sqFvZtviD0l5MEVOH0oI/5osBF8OiXpC
            qe5cEYD5wt4BJ1afXcqon9+TPqff8iyZfg3UzjMjbNDK12ksI8JLHl4JuSAqSY/2
            7z/ruIIy8yw/dVvd8rjUfPIViffjtK4cn9HQ0ORTAO8h9Dg2UDiOmmNfUXTfWE+v
            tTlPo3IqvDTmDLQDYC5WE9sW9SZUu9m2W7hDRk7WPmGYLgTzDQZWiZFItLZ0CNeI
            TteiHWHDQiaQlJzeyq0tAaOJd5sSbEbcGkAGmfLuD2M9UZ9MTNmmhv+0EBcJJsUm
            OuXAK5OdFlioVeVNbO7vt6hRKo7YHAmiGynwLrCdpGXoIF83/cAU9qMDMWT0GdyH
            kM2D3W7AHTYXIUy6UADfmXQZygPERf+n2GUMy2z3nqIpjOcdI5HPGa3RDehvidbU
            aAEJAhWjkICtaAb4I67iGmlqRVHno8DT1shUEpEGKVZIvpKPbjiITcTqku2/aaKp
            Cm/zkh1a/ozWukAHl5R1Z5TlevGB1bGAjasWxLcePVjjNbu0aLE585PD90Ci8ptY
            l2p96EwvCwNw
            =MRMf
            -----END PGP MESSAGE-----
          fp: D6E328D82432FB01BE3DFFA7991B5EBFE76CE170
        - created_at: "2021-09-27T17:49:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZrgHWJPExZAQ//dXwic3BRtUTBg+DO30vyMlBgLBMmMwTESFZPAgKSc8oP
            h1CbVzc3uKHdPc/H7HRouEhUwW5GK7yOWMAo2BXJyG6vX8vNobgje/ivDA/Ztcx+
            dDzpTmrST2eozDeYT0Pfq6JKQGPVPbUdl5yB9y/DXYGssZlXU2QLflPTSQKFJ80/
            zFaV6hNz5y7bHUTgUnSj20/m+Pjs1a4TIfQphdTnyw4tCBtVlKgeG5cPziTdqI5X
            MTL7rBqqLvndPQBL5BvUCBkhfybmtaO/KQc9A12iFx3+iSQz4GECrgBTLEwNlog4
            41rCS/TAhvwvdvsWB7YpL3qBFEybGAZTTyeMtXoe0sL1ihfGfzZTuwdk08CkoFnb
            lwBfytFwTb1VHAA5euthjXTAv/kSavkB3swX+x4qn6m9HEvDcKTUv+Ddg8XvTOo8
            UWt2oAmzab2YVHhtj+wSFpZk4p4wjvfSSKO9uUNSCTlTcoB0DuCPhyigTK+fiflL
            Sjq8VFVglLfk8Li1/nWWFjQs4iRMGVtCkyg3L1bCiMOe87bRvo9qvQQziddkLL9m
            HKwhEKtDEvo/4g9gQy8Rs4uoRYT+bOxYsI8G1oxhpAJ6fYBkVldOZYna8WFfeYUo
            mBZlmp1/HmgH+p17OQZKsnD/d/+gnIKflo9To8Je6F9E3ad8cHdWi6RmMk9+3+rU
            aAEJAhVt0D8NgneaWDxDNLf4ZOov0+XHMVHzi2g2wcTMlaDw7FfBRtkl7mZFTNV6
            ovKXHWGRqFuCHXphaM3qMdevBg6HiNZeal2iS7ub13AEQgNGOTuYVXa1ZmWBv6ab
            DsGwcFcgNYw/
            =xrVI
            -----END PGP MESSAGE-----
          fp: 8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
