---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: 192.168.1.147
  METALLB_LB_RANGE: 10.10.10.70-10.10.10.90
  METALLB_TRAEFIK_ADDR: 10.10.10.70
