---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: website
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: nginx
      version: 9.5.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.21.3-debian-10-r0
      pullPolicy: IfNotPresent
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
    containerPorts:
      http: 8080
    cloneStaticSiteFromGit:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/git
        tag: 2.33.0-debian-10-r14
        pullPolicy: IfNotPresent
        pullSecrets: []
      repository: "https://github.com/coolguy1771/website.git"
      branch: "main"
      interval: 60
    ingress:
      enabled: true
      certManager: true
      pathType: ImplementationSpecific
      hostname: ${SECRET_DOMAIN}
      path: /
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: "traefik"
        hajimari.io/enable: "true"
        hajimari.io/icon: "application-outline"
      tls: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
        namespace: "monitoring"
        interval: "10"
