---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - system-upgrade
  - auth
  - flux-system
  - monitoring
  - networking
  - storage
  - system-upgrade
  - tools
  - velero
  - website