# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cmmszBSk3eRzvJugrRqCDM4Zj+/NgVLcwPNel3oG1lGIHiELs4GYzA==,iv:qF0J/Nj+V5f986e+fTbBehejJtwr2cC/XznOMIrvf2A=,tag:XNcTza0N8xj2Pw79apev6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-17T23:45:19Z"
    mac: ENC[AES256_GCM,data:CH2QzJ/qsWBU/5k/c6YUMUHecCH9ipEWeLDcbD0MOpKTWwGZ7QQGR2bJEvigA7Yo97v4hbbM2Cu31AhcngXwaok04/x7iptoWsgal1NR66zNP5jE8FYzd+nAYpGWBs+hc0Wdgk/UjISnyRSs4GZ64Um8irLlIm/a6ajVrsLgHUA=,iv:t3zzaegwfvsDxRa3DYQCvfK7Q2C5QHqW39RTQG0QOZs=,tag:RN5zL4IQ/cgY224bRAOppw==,type:str]
    pgp:
        - created_at: "2021-10-17T23:45:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3/0YQQPIqO9ARAAnW9ItA4X6sBgPU9DjgJns0XJ41adyVkxZ3h0Tm3C8cmK
            qS6A6LtoKrx4QIkIBsFoKXymkoBuSzeXW7GABF42XnR9t9sdQVMjb4Ac+6t9DCLs
            4sXx0CWJ6/8k+/fqYxOkB8pzHFknL4wD0pLUkPgB/gK6b3FpvYVTWh18LK6uhZ0j
            BTx4Ym0qdlXU9/ypsklSF//8+eFcYwKahBZ/G88W/gi9VtLVFtq71xJJC6KYtW28
            esZjrv38AWQgH2fWFisj7HL/d4CStY+ymw4w+MOH6/LbSfMzDXR6JZkpGSvXpxuJ
            Rh6HBr3kEBTG6Uy8Fp27ZrjVHmcIbsRXREJiYqkVH1tvkvPlIWkifmnHBFZuhAwX
            NX5+SueemxLfKtgBSzJdIRyt9IUkVIpCQCJvCnrns1WOqgBJb6Ia1rwIqGG7tSWn
            WNwVj64z5No9QE9jt6SWw7dt41CVUnOJn7pjo7pWU23S6Fnennn+hD0esqJpaY9h
            uNMjtYcfCJiuiDNvtC2ffsIYRmmgRhgvcq4dV4pygMvhZBafHdx/kvJrLKQFUW3b
            Reaf1n+T/IaJ4ZWW8PMd4QuIGmFIjp51N6dNSjmwY9m++fiOphSVZ71Th33Wz+Lk
            2FFeYfVB8BZdL2R5zg2cxs9nJDALnxt1nQmymAt+XRbttVeKBgcV2OWLDTJVxjvU
            aAEJAhUUtl59RMOnNm3uFyq/SGKEfzTRWBG9Y5eqPM4kL582fkmIltSL10+arHt1
            YrmEJ/c2+P74Jj382JcIV4DakvorCvb3t2npCJoB2IRpa8JmU0yDavDF9jWnOVlE
            jD3iMVygbJ+m
            =P1YN
            -----END PGP MESSAGE-----
          fp: D6E328D82432FB01BE3DFFA7991B5EBFE76CE170
        - created_at: "2021-10-17T23:45:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZrgHWJPExZARAAtKmqnG1nJ/t+KQiwWi6N/tptGFMDvKOoaCDArMNBvfLg
            UElm/iZT1WQ5aguxempUOgA7VbohRCv8AQ0OV91GbIbRo0Gm+iE7sWqSx5RbNejG
            Ek6ViRGtC7gMrEgn3FYC/7QEYKME4diRJVdYsa1EMhqrI8HzFmeB0UPiX7Vzo6VA
            WnYF/yoj+M5zr7kF2Y6V9Rk0Jd/Kx3FoEe3YyEh7RT9Nx5Z3pYb+yDL96yDC5vff
            qZF4Dk4HZg4OmChOj+A+8EexK0Gd4lDLC5JTa1kwpEIHf0d9fhV6pB8xAnlqQMZp
            TeAGKPYPPIFhIG+XmjNPLNJv6SD8o8v0IROTT4UVPgJ4ylCbPQnyjwkQpnAKhbEw
            25SvNyaBCEyDcigIS7VVSU2MnhhtxULH0A1hSZF9MbnRVGNNOHZNsG/dKjFMC2dr
            GMaWiOeecn0ZUZjhW8FnkD3xPoabBhQG+qwuf66SQuXLqerxCKz/Imh/z12M3oim
            4isyAavrkqCmDHPhjqH0L/mZvzJeX+fCzFKNPlx7HtJnNXfjkc/6r1sOtbkMkCt5
            6bMjISfzvHFYnhg90tabUeDr/WEZnu5M2OhKDrEa3TLM0GqctB0+DHkiwB0qux6s
            eQTL1XXXNKwA8XAbpFxAiBy4est0JckX7VIFsqn7L2T3A9ww/Dns8ftxJqoNEoXU
            aAEJAhVY/jgRBWy0wbODpiPo5ay2+Y4L1H6EpWqdsy7/4dS6YKTwlxzkHNK1r53S
            ilJVkNOTc6vbCJJpUWRg50hqa4Lpxo5mv1SuEJiPsXNe/eHy6Rot2UFPVFrjRnZg
            PP/avVKbeNfP
            =FD3k
            -----END PGP MESSAGE-----
          fp: 8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
