# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:mWosJpgLV3VrkGRxGEIEtEQBuixRiEN59eQGF/a8IMJ2i2RQQA==,iv:2x2yjbPm/QiMHztbh/zslvUJ5PSyz8RMfTsdhykETVg=,tag:pOrdbHjEWiV7bkWPpXjS1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-17T02:23:27Z"
    mac: ENC[AES256_GCM,data:LHG1CsY2mLVWEV0ejuViUMx14+YPT2CISSkoGQiL9vkXk9ZrOmRtCz6nIr8fl7YCxqJPlyfvUb3QnrAZMpTwQucdimwU99JhlwyBYZgBm1N32VGqiuzdyMNTnXDmeRQAMIvLW10c0SeKUI4jjY2jb9pWhVjrm3Z9JvYtpM0uv6o=,iv:QM1Rr5wyokYijIheRn6IqHHFgY5fY/dou2qdkWza2XQ=,tag:9sUVWaQJG4uL3ifnM6Nw0w==,type:str]
    pgp:
        - created_at: "2021-10-17T02:23:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3/0YQQPIqO9AQ/6Alf9chrisczaqTTlEoHemF1IMxCP6o5q1XlWc6ZjEK6X
            QYPpxJJOkJ8BCGr2Ds7rpccpTawFtuEnMeRWSHHfSCpA7B2Xq7ornF9n4zLsF4Pl
            Kn1DsFQU7OS1HHOqmdMbGs729OQOviZ74oI1O8orPON1C253eKOmaADUsbfqeNgs
            ShFC7kJ4eXYbUThWxWG8vkYtPf5mGBRU7KhBJ3K64njRzQS2yGG7KXOnsLScnMxz
            t6W8EszzBLGuJTedMlo9T2u877llqdtYrZMITDlq0slbzoG15hjRYoWHzEwzkNCU
            LRmmxio+Q49N0yEpuRw+qZiTtDcsmbu1qHCLwb1cBqUYL9Ero8M5EyMTghM0rkAg
            TBTZ/Il6BwqdNr8QW73XCi8rvyXbOVguI1wOHefZrTvOEgIraQT502gnQuziJuQ5
            WQ6xtqtSfp3/7IwuZOCtpUMtTQToxrp9AXt+/fLrUsm8zq81W6hGc3IuSuDsKqXK
            S3ZAysAo52cJEnLCwVAJbQCJVoe9Nmpey7pZc2mGqWeoijrZrXH0RHIIMxfsL5mp
            CTQoJQZXatg7FjC2PiIMLCeUWGrzk4t+2Muam14GjwS7OBMRNzLUliSIreFx2h1n
            Ijy7ydnYv0CVkDl6UypUVjnxKZtn0iSAWSnOCUp0SFuZ6GJVWzBSOxJAru85F/jU
            aAEJAhWLV8i4tmaAiZBpTFczxLpqZGR9B+GgFgq9Fl3s2vcvaI+KYvcxeQV9KkoK
            UDnlqEXned6SEWroVk5FrtEVgAcpVBQnEXUkXhZDmWZiVfAkKmwDrAAtpozDNLq6
            yGHGv+jL5Ji2
            =ygTT
            -----END PGP MESSAGE-----
          fp: D6E328D82432FB01BE3DFFA7991B5EBFE76CE170
        - created_at: "2021-10-17T02:23:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZrgHWJPExZARAA4u8AXaBddd/ruk0uEPOfIteLwMFb/frl+EpvJmhcf+mo
            dFFOUyF28bMwD5T4/ZEx0aVZElkkARPODuxZ8uRQDlAYVTih8iJRMZo9s/o57IBQ
            9dzIagdcR29Jk8dg2pa7yevga152MwmAkJVhCZgYaenfs/RDImtm1v5rB8FdPfIP
            19R1a/a3QE41XLdSMon6yKgfdKcNgTcvZtEtOon2Am0B1313XNmlQFmzwwLfqU2/
            pad0eTz3agkSXXqMWPdVqx0ugB8wM7nhyFDYDYPhlxxih/x7az+pHL5QGme6F9mU
            1GSrkM0YMA6OqPcDeHFBh3+F58KhANe3P/SJWQfZochyg9IZm9FR/QhJTfQXzzfk
            QnuzKd8jCIa9rVpSN/kHCc56Mcp5+ctMikJzJcMVM66Q/MX6YF3K2eUDTQpxkPSa
            BWH2+LK5rtirJzcJ2rxc+WL0HcOGwCT9gVtKEBZZ/ViCzORDHPXLIV1bZAZUBYah
            K5uzwQqOQQKyZzd8p49B9X4J7Iw/92WN+xFqKGtkcTH1dOXNmTPExlallMEm6+wr
            nc7A+CNPtCqG5K+gICfACW53ffAZH9vodEODOmQBCt9XkRBUKWcBxQQpNPsncBoS
            qGcrkmAAXR7UPZ+SzZ0nQZr/jkqfFLoRqr6WSiw6WAA/xjU+ofLHqsVll3SGGpbU
            aAEJAhUJcwE1Vihlq9rHIf/I42Y7iznH3wEKL3W1TeCQsgL3+V2JS3cTh287zIdx
            LG08DEebpvQP8ru9IUisN+Zhx4MfZl66v+m010+54xFfTjDN5M5jY0T0W/cpLZ79
            xEuodu3ercVz
            =wxr/
            -----END PGP MESSAGE-----
          fp: 8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
