# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:wTO9FTaDk6X/qyc1SshfF/aSOkOKAMV12FSWnWZuYIRr7LLe2w==,iv:UJbnVy52WqELyA0nNkddHF+3BVT6Jgmqg6Qgwsa82o0=,tag:+KAHLDPw9rjObYnbpUE0AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-02T16:48:50Z"
    mac: ENC[AES256_GCM,data:EujiDf6L1QC+TBCEYHixgsBMFSdLgEvXe6nuhcs5Tkcmlg18WuPY6gOD4U7ck7/VW2Vf/d5xP6NQOq/DTE5NqekyOK75TjEB2C9d3tC2M8S84yJ1G9FWIrtBsRdPTELovi9AM+chx0vqkoOYReIr3weoP2Car+ot7f0V5uHt3fQ=,iv:iadEqI/4TgwCM4U2hRy5HEXFGkBN+Clndtjxn0OAgUc=,tag:lBUfiTNNoHzXJAOP9eUOIQ==,type:str]
    pgp:
        - created_at: "2021-11-02T16:48:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3/0YQQPIqO9AQ/+K97HD3Jr+VeAH7CqMSWQE0Wi9XsQxKQ/liMYd0jQad+d
            ZzYRSefgSlBuSjPPpUxVB0bBQtqm2pp1vFk3GwkDuqAE3qNFtMgIRWD3MxroJ0XI
            TjbWnB4K7CpbaSH6/BSTieTc9IruQgH9yGXloUj9g/lRz8PE13s0IWov3mQN+Joo
            zskvUZvX4g9MFv0y89ZN+ADQFoQIVbb8TRpdeGeXqMh/J8HMs+bNARXj5vS8Sh5E
            dfSh5xFikaNP3Kl4XEuK7uBO65xjVo+PrCF/LBNZ1wt1auqBOM5VKqaNx8ol4H4N
            q3griPUJimAPmWXP9VJBHTh2KKlk4OJCOCrpq1SgoE1dE5VfcJIIBoTQJfGLNbF4
            SwOgo4aTwX+CIaMrlGXxC3x44mkQ6AC5vDpo1guWxF+IAuQmEHd7fapCZ7hLtOW+
            yfAU41iY+wlXFx3VrgkxuykrQCZa/GXGxUDiRpfIX+gy91w8iPXoFzOvmJI6uO/y
            WPVDN7qXmP195Rbux/BQiam9h0kTi7oR9kOL5dvKzxZqlraZFNaNWgF/3PB3ks0y
            EkT+3z6esRXvx52jcNetvjInXkk13N1c+Z9pLxQe9IZw88rRqMbB5anpoNJ5Kj6l
            EVK+iZrQtQi9hFCln8euAf36QJ/Qd0wmJJ5jutEXZNUXketPTsVhxrHp6vVG3uDU
            ZgEJAhCxO1C5rlkpleImW/N1b4RdRJnIN+hM5x7SEFEWMwUauCHGWx/MtD7+GYAP
            SeaoI94VayE+yvECAya3sR4tXst46pWzM4xZyyE4h0pZkiUVQR8749g6UlEn7qWi
            eFI9DQRAaw==
            =mWRR
            -----END PGP MESSAGE-----
          fp: D6E328D82432FB01BE3DFFA7991B5EBFE76CE170
        - created_at: "2021-11-02T16:48:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZrgHWJPExZARAAhEGEt00yxL4feHV7TOQ+jsN5k4XYIP8+CA9UrhQIfgUy
            cbR/EKZQY3HqWBfg23uMXW7B1dGB6dA/gpbcYIRxGpeKdsnZZrS4cbjPlRYKPr5q
            ZCxWbATccBiv4M6oat+ulvIPDh44yRp0i5cSDw1LYzOGqt+TqfSuCEdQi1siDnDv
            ljY4B90vms/25IVZF1h6hHo+rQbemP2Aq0NWIlmOEdvW1qBhxPu2lEA09HS1lpiM
            L1fQJILnXYJlSgmA6Ob5Iyjnk/PJTRMKyJAEXV1JEC1A6uifdj0f0ShwCiFFuz5y
            WH8J3OTOrMO0DsJ2kEeYqqPdGeIrhyl3tLSe1fUGWRpu87go+4WayJhQpjDcG405
            MfnK0VwhqfVRsVuiCwk8d0n9meEhuCBYGylYvlauH5ABwEFkV4p1qKck4T2pJvPv
            45/s1jELWH24z+jtLUo5K2eUjzeCODUoq5g5UjWgRyOMQiR5731oYystB8A7+E36
            uJ8EtXKts47e2WO5kA68IBYDhoRZKq2XGcMoXmj5x8eIPV+z+UNitgaRgF7y4Kg/
            IS47Z10PLqT5BWOtkEDfMQR18I9ST8NExKg3/aL7zsC6lfaN+0w4mLXlep1fnZrn
            FJKqBFVJe7d6Yv6nLOiCN65izlzjZqeTiyGEeTNT7IqJ4ypeRyIqt3S8TJnq6+bU
            ZgEJAhBcRxblh1etho+b2IFbhJUpmaPAp0amw2PifvRI0SOZQ8m4SHtODjqjxXdZ
            4+57xiXPou+l1epmNR1pgJUgMiE63cHQMztlVKpPG/+4yqXFcO3EsWYYN9c4NjE/
            O3+13LzK7A==
            =4oG7
            -----END PGP MESSAGE-----
          fp: 8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
