
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
    ##TODO add config for botkube
stringData:
    comm_config.yaml: |
      communications:
        discord:
          enabled: true
          token: ""
          botid: ""
          channel: ""