# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:PIDDdaY4TH1/I7wZNlwTW7JHSYje27I22IZjawJamEShhhGv89rZSg2kFRzly78ltEu1YXucYqxRjAh+BCXMEWRhz7b6Am8cGYiq+171M+lqZYrJ2GxZPBzh/X1Rqpj401jTFjlPxgFEEYX6xcDDlh7YiMLYU//fdPCX0EfWb9612yfNkR5uyb2syqLGzDEJJ5xNHbKpM60wpj6X34xXiKF32w2C2C+A0tf5gnztBx8RBWRAESDO,iv:iS6zu65x2mV5p4pKE22AkarALh5yuKFDKtB6aIC8eXc=,tag:vBhBC4rbMTeWFkdxheOIVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-17T23:19:26Z"
    mac: ENC[AES256_GCM,data:FAnb9mc7VLa/0t3PVuceWVehD4sA2GzRMFJ9ws6vsH9N2GYva9PdZZVR14E/T4MfKk5dI9lw8QfYzwICheRVMBZ9C33mlx1XP9KUxMPOG91UOWF7Hea8IUCFx7FK/nZaf7KNW7J7kDS7DsbkRK2ovtPARgtVijKtNNjAeuJto14=,iv:Y/W+Wn9F7KQ5k6QtzgAAP0u0GjKdC7V+M4Hd0Toy5Pc=,tag:V/a/b82d3jLBAfSEIK69fw==,type:str]
    pgp:
        - created_at: "2021-10-17T23:19:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3/0YQQPIqO9AQ/+NwfuQ7MIhPL3ck0Hdpv/uKZAeCNHY3LDeI66nIe8RIv1
            NahmEMBpRjW4X8wC1fpLC31ygW6mmj8oKSn4SWazOcAa/if2U+VF/2Wjpuf9mS8o
            V6RU1yBo50kV6PTa7v+0H2nfnYTR+Vlm7IbzPrgwIbFowuoaZYwpmNk0gdg5AkM2
            4XFWNP+iau83c73gICYDd+kHUTF0wfkbl6CPeilVLMCjYYx3fZ7MMIrosfhannpp
            Kyf4bEZTaKXqxFY68E9Wn1GOtZ+YJ53a1ssYYaWSnzPtLyyhrZenEuo7epYzPHYP
            Tpqpc2tjwZnRsRFvowdxQFQYFY77PM2XpVJ+xM5Rjo+6eqhrCPjUld5qPxyitVVU
            msKkzLbImj6Qd+nHQvz2CQB9P7XKeKQxhM0UBmZYjnoxZ8ZZIfOr17PI08fUZUni
            H2qWCL8pODfUZYJGON0mFlZ1x7A1t9jcmPsYknyJ2wC1vImj6yryVr/1OMxpZTju
            ohDAvIbP53i4roKjq/IDeQWB9PMrmqUIAEvbxgjqSBYgCGFnEXqYJFnJTyJLegdI
            jeJiz+d6x1NRCmhgJPAPV2dVLOHi8y7oIOOdMbWPyOHcrcTX/1crDs5lD4sojmWe
            w8XADhKeJD9WcYeNhPnft89EUsU+3JkaFPPrKrgF9GlQ7O7fkb54U1KXZMtrd73U
            aAEJAhWrFDqoqUghhXPSwHThP//HY/ren7+YTBlhUKPij9mqf6hJ0huMyJngzcxw
            91/EmnokAdRnFWCQaE6dY19kgICutwnPk6l8VTIGEZ9JLg2qd2W6Y7K0XCIRsBdv
            bhCYMSfqOqZK
            =im0S
            -----END PGP MESSAGE-----
          fp: D6E328D82432FB01BE3DFFA7991B5EBFE76CE170
        - created_at: "2021-10-17T23:19:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZrgHWJPExZAQ/6Agio9eCeQEkbvnbBn3i+0ZqnObrroVAIIwzEtlGEy/wN
            V/Y4NUlDE1rB8hhounkCSTfJoZ4fdsOk1Y5hNTHTT3P2ysXHwnwdurQ/+F1FkeAH
            mXHG+1KQvMO3QmWR9qYTXwrdSABp1XBukAgMCYUI/Qh7jkOCS45hiY45GqPTXgZJ
            i9BuDSlKeuElvmL8WRZT4JYSmxgRN5KNuyfdcbgj/br1b5V3Jms3GjbirxkUIcpB
            wG0LgroUogZ96JBugJN9HbgNjY51A9bnqezuT2cn64HiCADIW/qr7JBnsPZTXYki
            fbwZNzR0ttXfRv6QveviOF83uh5XXHaU3KLkGM9XpQ8BUgIB0QAFoWoMOk+kcz6M
            uQot6crDOsfDZQI5jGZdRz5zzqbOhPgUbMJbgwJJnyeyOw4PLHwo04XhTZEcEDYS
            721YRIUf665yqxm0k4EVz2rOcAli9iOw++/jFed0NPj6BFm9AR9HKPYb7Bb5YdnZ
            gzw37iZx81cC6R40r/Z5by04zrwQAClxh5BFBV1eIGscugP1YTAX8jAho4xP7Gle
            r0N4bUFoHWe+3vTz0b4XJDWSi7S3OtsL2PmYJtmpBaddjtKB52WAi31wVudg+SV6
            JZal9AGdVLW9d9mMg1XWLS0vQ4bohi3XY21Iw2lETqvu1tKHY848CSvETxiRTAPU
            aAEJAhWeQ8i8VPl4TGiyOM4ui7vL2Z3F0eHOTNwgwn20CVMGa778/dmIae5EPDRH
            hUqyqM/McC8AxfwutyId824ZpxXTy2Z7RU0q8rEj38DoCpeWMjUiXBaDHqpoBsic
            5wKGtQQNCVCW
            =ZHtH
            -----END PGP MESSAGE-----
          fp: 8AD15E7264D13B2F0DBA993A2D5520C7A1FAFB9C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
